services:
  app:
    build:
      context: ./docker
      target: development
      args:
        APP_UID: 1000
    restart: always
    volumes:
      - .:/app
    ports:
      - 8080:8080
    networks:
      - default
      - temporal-network

networks:
  default:
    driver: bridge
  temporal-network:
    external: true
